import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';
import '@/styles/globals.css';
import { cn } from '@/lib/utils';
import { ThemeProvider } from '@/components/theme-provider';
import { ModeToggle } from '@/components/mode-toggle';
import Provider from '@/components/Provider';
import AppBar from '@/components/AppBar';
import { auth } from './configurations/auth';
import { Toaster } from '@/components/ui/toaster';
import NavBar from '@/components/NavBar';
import { AntdRegistry } from '@ant-design/nextjs-registry';

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const serverSession = await auth();
  return (
    <html lang="en">
      <body
        className={cn(
          'min-h-screen min-w-screen bg-background font-sans antialiased',
          fontSans.variable
        )}
      >
        <Provider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <AntdRegistry>
              <div className="flex flex-col min-h-screen">
                <div className="p-2 h-[7vh] flex justify-center items-center">
                  <AppBar />
                </div>
                <div className="h-[93vh] flex">
                  <NavBar />
                  <div className="w-full h-full">{children}</div>
                </div>
              </div>
            </AntdRegistry>
          </ThemeProvider>
        </Provider>
        <Toaster />
      </body>
    </html>
  );
}

